apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-development
  labels:
    app: zts-cmc
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  #clusters:
  #- name: cluster1
  clusterSelector:
    matchLabels:
      environment: dev
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
