apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-development-subscription
  labels:
    app: zts-cmc 
  annotations:
    apps.open-cluster-management.io/github-path: nginx
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: webui/gitops
  placement:
    placementRef:
      name: nginx-development
      kind: PlacementRule
